export const ADD_CUSINES_REQUEST = "ADD_CUSINES_REQUEST"
export const ADD_CUSINES_SUCCESS = "ADD_CUSINES_SUCCESS"
export const ADD_CUSINES_ERROR = "ADD_CUSINES_ERROR"


export const ADD_LOCATION_DATA_REQUEST = "ADD_LOCATION_DATA_REQUEST"
export const ADD_LOCATION_DATA_SUCCESS = "ADD_LOCATION_DATA_SUCCESS"
export const ADD_LOCATION_DATA_ERROR = "ADD_LOCATION_DATA_ERROR"

export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST"
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_ERROR = "GET_ADDRESS_ERROR"